### ISSUE TITLE
请问此处是否应该是dynamic_pooling的实现？

### ISSUE THREAD

**Issue by airkid** [sanmusunrise/NPNs#1]
学长您好，首先感谢您开源这份代码，我从中收益颇丰，然而我对NPN_TS.py的其中一行有疑惑：

https://github.com/sanmusunrise/NPNs/blob/3a43709d3d18e383b4d569eeecbeb5a0cde33881/src/NPN_TS.py#L150

请问该行是否是文章中提到的dynamic_pooling的实现？如果是的话为何只有一个reduce_max而不是根据candidate_trigger进行分段max_pooling呢？

**Comment by sanmusunrise** [comment]
Hi airkid,

   你的理解是正确的，目前上传的这个版本是直接做了max pooling而不是dynamic max pooling的。因为我们实验中发现是否做dynamic pooling对结果的影响不是特别显著，因此为了保持代码的简洁我们就去掉了。

btw. 我们在tfnlp的代码里面包含了MaskLayer的接口，同时我们模型的参数中也已经包含了word_position和char_position的信息。因此实际上在我们的代码上实现dynamic multi-pooling仅仅需要增加几行代码即可 :)

祝好

**Comment by airkid** [comment]
明白了，谢谢学长！
这份代码确实非常简洁易读，代码中对tensor维度的注释对我的理解起了很大帮助，再次感谢！

**Comment by spurstong** [comment]
请问一下span_type和label_id代表是什么啊，能提供一下几个数据样例吗
