### ISSUE TITLE
邮箱（hongyu2016@iscas.ac.cn ）是否还在使用？

### ISSUE THREAD

**Issue by larryzk** [sanmusunrise/NPNs#7]
您好，感谢您所做的工作，我通过邮件联系了您想获取一份数据处理文件，但是没有得到回音，担心您的学校邮箱可能已经不再使用了，因此来询问一下，打扰之处请见谅。

**Comment by sanmusunrise** [comment]
您好，感谢您对我们工作的关注。

由于前一段在休假，所以可能未能及时回复邮件。现在所有请求数据的邮件都已经回复。如果您还没有收到数据，请再次联系我。

**Comment by larryzk** [comment]
非常感谢！

**Comment by ll0ruc** [comment]
您好，我邮件也没联系上题主，不知道你有没有联系上，请问能分享下ace2005中文数据集的切分文件吗(train,dev,test,)分别包含哪些文件目录 @Laityzk @sanmusunrise

**Comment by Jone-zc** [comment]
您好，我也没有联系上作者，抱歉打扰到您，不知道您能否分享一下数据处理文件，我已购买ACE2005数据，希望能得到您的回复，个人邮箱如下41627026@smail.swufe.edu.cn @Laityzk
